apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: l22xlt8vp-go 
  janus-idp.io/tekton: l22xlt8vp-go
  backstage.io/kubernetes-id: l22xlt8vp-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: l22xlt8vp-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml