apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: l22xlt8vp-go-gitops
  description: This is GitOps manifest for l22xlt8vp-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=l22xlt8vp-go
    backstage.io/kubernetes-id: l22xlt8vp-go 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: l22xlt8vp-go-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:l22xlt8vp-go
